image: docker:latest

stages:
  - build
  - staging
  - production

maven-build:
  stage: build
  script:
    - apt-get update -qy
    - apt-get install -y maven
    - maven package
  artifacts:
    paths:
      - target/*.jar

deploy-staging:
  stage: staging
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_STAGING_APP --api-key=$HEROKU_STAGING_API_KEY

deploy-prod:
  stage: production
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_PRODUCTION_APP --api-key=$HEROKU_PRODUCTION_API_KEY