spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stogacs
    username: root
    password:
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
    generate-ddl: true
    hibernate:
      ddl-auto: create

hibernate:
  show_sql: true