spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stogacs
    username: root
    password:
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

hibernate:
  show_sql: true